config/urls.py
# import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static


urlpatterns = [
     
     path('admin/', admin.site.urls),
     path ('', include('core.urls')), 
     path ('', include('accounts.urls')),    
     path ('meetings/', include('meetings.urls')), 
     path ('contact/', include('contact.urls')), 
     path ('project/', include('project.urls')), 
     
    #  path('__debug__/', include('debug_toolbar.urls')),
     
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

contact/urls.py
from django.urls import path
from . import views 
from .views import  CompanyListView, AddCompanyView, CompanyUpdateView, CompanyDetailView, CompanyDeleteView
from .views import  ClientListView, AddClientView, ClientUpdateView, ClientDetailView, ClientDeleteView
from .views import  LeadListView, AddLeadView, LeadUpdateView, LeadDetailView, LeadDeleteView, LeadsUpdateView
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'contact'

urlpatterns = [
  
   #company
  
   path('companylist', login_required(CompanyListView.as_view()), name='companylist'),
   path('addcompany', login_required(AddCompanyView.as_view()), name="addcompany"),
   path('editcompany/<int:pk>/', login_required(CompanyUpdateView.as_view()), name="editcompany"),
   path('companydetail/<int:pk>/', login_required(CompanyDetailView.as_view()), name="companydetail"),
   path('companydelete/<int:pk>/', login_required(CompanyDeleteView.as_view()), name="companydelete"),
  
  #CLIENT
   path('clientlist', login_required(ClientListView.as_view()), name='clientlist'),
   path('addclient', login_required(AddClientView.as_view()), name="addclient"),
   path('editclient/<int:pk>/', login_required(ClientUpdateView.as_view()), name="editclient"),
   path('clientdetail/<int:pk>/', login_required(ClientDetailView.as_view()), name="clientdetail"),
   path('clientdelete/<int:pk>/', login_required(ClientDeleteView.as_view()), name="clientdelete"),

   #LEADS
   path('leadlist', login_required(LeadListView.as_view()), name='leadlist'),
   path('addlead',  login_required(AddLeadView.as_view()), name="addlead"),
   path('editlead/<int:pk>/', login_required(LeadUpdateView.as_view()), name="editlead"),
   path('editleads/<int:pk>/', login_required(LeadsUpdateView.as_view()), name="editleads"),
   path('leaddetail/<int:pk>/', login_required(LeadDetailView.as_view()), name="leaddetail"),
   path('leaddelete/<int:pk>/', login_required(LeadDeleteView.as_view()), name="leaddelete"),
 

]

core/urls.py
from django.urls import path
from . import views 
from .views import IndexView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'core'

urlpatterns = [
  
  path('', login_required(IndexView.as_view()), name='index'),
   ]

project/urls.py
from django.urls import path 
from project.views import ProjectListView, AddProjectView, ProjectUpdateView, ProjectDetailView,ProjectDeleteView
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'project'

urlpatterns = [
  
   #project
   path('projectlist', login_required(ProjectListView.as_view()), name='projectlist'),
   path('addproject', login_required(AddProjectView.as_view()), name="addproject"),
   path('editproject/<int:pk>/', login_required(ProjectUpdateView.as_view()), name="editproject"),
   path('projectdetail/<int:pk>/', login_required(ProjectDetailView.as_view()), name="projectdetail"),
   path('projectdelete/<int:pk>/', login_required(ProjectDeleteView.as_view()), name="projectdelete"),

  
   

]

contact/models.py
from email.policy import default
from re import T
from django.db import models
from django.urls import reverse 
from tinymce import models as tinymce_models


# Create your models here.

# contact 
COMPANY_TYPE_CHOICES = (
    ('CL', 'client'),
    ('F', 'fournisseur'),
    ('P', 'partenaire'),
    ('CN', 'concurrent'),

)
PROJECT_TYPE_CHOICES = (
    ('EC', 'e-commerce'),
    ('WS', 'web site'),
    ('WA', 'web app'),
)

class Company(models.Model):
    name                = models.CharField(max_length=250)
    industry            = models.CharField(max_length=100, blank=True, null=True)
    annual_revenue      = models.DecimalField(max_digits=20 , decimal_places=0, blank=True, null=True)
    email               = models.EmailField(max_length=254,  blank=True, null=True)
    mobile              = models.CharField(max_length=13,  blank=True, null=True)
    website             = models.URLField(max_length=250, blank=True, null=True)
    adress              = models.CharField(max_length=250,  blank=True, null=True)
    rc_code             = models.CharField( max_length=150, null=True, blank=True)
    art_code            = models.CharField(max_length=150, null=True, blank=True)
    nif_code            = models.CharField( max_length=150, null=True, blank=True)
    nis_code            = models.CharField( max_length=150, null=True, blank=True)
    responsible_person  = models.CharField(max_length=100,  blank=True, null=True)
    source              = models.CharField(max_length=250, blank=True, null=True)
    company_type        = models.CharField(choices=COMPANY_TYPE_CHOICES, max_length=2, blank=True, null=True)
    project_type        = models.CharField(choices=PROJECT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    logo                = models.ImageField(upload_to='companies/', null=True, blank=True)  
    collab_start        = models.DateField(blank=True, null=True)
    created             = models.DateField(auto_now=True)
    updated             = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("contact:companydetail", kwargs={"pk": self.pk})

   
DECISION_TYPE_CHOICES= (
    ('1', '*'),
    ('2', '**'),
    ('3', '***'),
    ('4', '****'),
    ('5', '*****'),
)


class Employee(models.Model):
    name         = models.CharField(max_length=254)
    company      = models.ForeignKey(Company, blank=True, null=True, on_delete=models.CASCADE) 
    decision     = models.CharField(choices=DECISION_TYPE_CHOICES, max_length=2, blank=True, null=True)
    mobile       = models.CharField(max_length=13, blank=True, null=True)
    email        = models.EmailField(max_length=254, blank=True, null=True) 
    address      = models.CharField(max_length=250, blank=True, null=True)
    source       = models.CharField( max_length=250, blank=True, null=True)
    project_type = models.CharField(choices=PROJECT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    collab_start = models.DateField(blank=True, null=True)
    created      = models.DateField(auto_now=True)
    updated      = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("contact:clientdetail", kwargs={"pk": self.pk})

STATUS_TYPE_CHOICES= (
    ('I', 'inrested'),
    ('CA', 'call again'),
    ('NI', 'not intrested'), 
) 


class Lead(models.Model):
    company      = models.ForeignKey(Company, on_delete=models.SET_NULL, blank=True, null=True)
    source       = models.CharField( max_length=250, blank=True, null=True)
    project_type = models.CharField(choices=PROJECT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    status       = models.CharField(choices=STATUS_TYPE_CHOICES, max_length=2, blank=True, null=True)
    note         = tinymce_models.HTMLField( blank=True, null=True)
    created      = models.DateField(auto_now=True)
    updated      = models.DateField(auto_now_add=True)
    def __str__(self):
        return str(self.company)
    def get_absolute_url(self):
        return reverse("contact:leaddetail", kwargs={"pk": self.pk})
    
   

    

project/models.py
from django.db import models
from contact.models import Company, Employee
from tinymce import models as tinymce_models

# Create your models here.


PROJECT_TYPE_CHOICES = (
    ('EC', 'e-commerce'),
    ('WS', 'web site'),
    ('WA', 'web app'),
    
)
CONTRACT_TYPE_CHOICES = (
    ('H', 'hosting'),
    ('A', 'annual'),
    ('S', 'semi-annual'),
    ('Q', 'quarterly'),
    ('AD', 'adverisement'),
)
STATUS_TYPE_CHOICES= (
    ('CO', 'confirm'),
    ('CP', 'completed'),
    ('PE', 'pending'),
) 
class Project (models.Model): 
    name                    = models.CharField(max_length=254, blank=True)
    company                 = models.ForeignKey(Company, blank=True, null=True, on_delete=models.CASCADE) 
    manager                 = models.ForeignKey(Employee, blank=True, null=True, on_delete=models.CASCADE) 
    started_date            = models.DateField(blank=True, null=True) 
    deadline                = models.DateField(blank=True, null=True) 
    project_type            = models.CharField(choices=PROJECT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    contract                = models.CharField(choices=CONTRACT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    contract_expiration     = models.DateField(blank=True, null=True) 
    cost                    = models.DecimalField(max_digits=20 , decimal_places=0, blank=True, null=True)
    status                  = models.CharField(choices=STATUS_TYPE_CHOICES, max_length=2, blank=True, null=True)
    description             = tinymce_models.HTMLField( blank=True, null=True)
    def __str__(self):
        return self.name
  

project/forms.py
from django import forms
from django.forms import ModelForm, widgets
from django.contrib.admin.widgets import AdminDateWidget
from .models import Project

class AddProjectForm(ModelForm) :
    class Meta: 
        model = Project
        fields = '__all__' 
     

project/views.py
from django.db.models.query import QuerySet
from django.db.models.query_utils import Q
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import HttpResponse, request
from django.urls.base import reverse_lazy
from django.views.generic import (
    TemplateView,
    DetailView,
    ListView,
    UpdateView,
    ListView,
    DeleteView, 
    FormView
)
from django.views.generic.edit import CreateView
from pprint import pprint
from contact.models import Company, Employee
import project
from project.models import Project
from project.forms import Project, AddProjectForm
from project.filters import ProjectFilter
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.contrib import messages
import logging
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.
class RedirectPermissionRequiredMixin(PermissionRequiredMixin,):
    login_url = reverse_lazy('core:index')
    def handle_no_permission(self):
        return redirect(self.get_login_url())


#project    
class ProjectListView(RedirectPermissionRequiredMixin,ListView): 
    template_name= "project_list.html"
    model = Project 
    permission_required= 'project.view_project'
    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        # context["projects"] =Project.objects.all().order_by('active')
        context["project_count"] =Project.objects.all().count()
        filters=ProjectFilter(self.request.GET, queryset=Project.objects.all())
        context["projects"] = filters.qs
        return context
    
class ProjectDetailView(RedirectPermissionRequiredMixin,DetailView):
    model = Project
    template_name= "project_detail.html"
    permission_required= 'project.view_project'
  
        
class AddProjectView(RedirectPermissionRequiredMixin,SuccessMessageMixin, CreateView):
    template_name= "project_add.html"
    form_class= AddProjectForm
    model = Project
    success_message = "Project added successfully."
    permission_required= 'project.add_project'
    success_url = reverse_lazy('project:projectlist')
    def form_invalid(self, form):
        pprint(form.errors)
        return super().form_invalid(form)
    def get_context_data(self, **kwargs):
        context = super(AddProjectView, self).get_context_data(**kwargs)
        context["companies"] = Company.objects.all()
        context["employees"] = Employee.objects.all()
        return context
   
 
class ProjectUpdateView(RedirectPermissionRequiredMixin,SuccessMessageMixin, UpdateView):
    model = Project
    form_class= AddProjectForm
    template_name = 'project_edit.html' 
    success_message = "Project updated successfully."
    permission_required= 'project.change_project'
    success_url = reverse_lazy('project:projectlist')
    def form_invalid(self, form):
        pprint(form.errors)
        return super().form_invalid(form)
    def get_context_data(self, **kwargs):
        context = super(ProjectUpdateView, self).get_context_data(**kwargs)
        context["companies"] = Company.objects.all()
        context["employees"] = Employee.objects.all()
        return context
   

class ProjectDeleteView(RedirectPermissionRequiredMixin,SuccessMessageMixin, DeleteView):
    model = Project
    template_name= "project_delete.html"
    success_message = "Product deleted successfully."
    permission_required= 'project.delete_project'
    success_url = reverse_lazy('project:projectlist')

project/templates/project-detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Project</title>
{% endblock %}
<!-- Main Wrapper -->
<div class="main-wrapper">
<!-- Page Wrapper -->
<div class="page-wrapper">
    <div class="content container-fluid">
    
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Project</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Project</li>
                    </ul>
                </div>
            </div>
        </div>
        
        <!-- /Page Header -->
        <div class="row bg-white">
            <div class="container bg-white">
                
                <!-- Doctor Widget -->
                <div class="card bg-white">
                    <div class="card-body bg-white">
    
                        <div class="doctor-widget">
                            <div class="doc-info-left">
                            
                                <div class="doc-info-cont">
                                    <h4 class="doc-name">{{project.name}}</h4>
                                    <br>
                                    <p >Company : {{project.company}}</p>
                                    <p >Active : {{project.active}}</p>
                                    <p >Follow up : {{project.follow_up}}</p>
                                    <p >Deadline : {{project.deadline}}</p>
                                    <p >Source :  {{project.get_source_display}}</p>
                                   
                                </div>
                            </div>
                            <div class="doc-info-right">
                                <div class="clini-infos">
                                     <p >Manager : {{project.manager}}</p>
                                    <p >Deposit : {{project.deposit}}</p>
                                    <p >Due : {{project.due}}</p>
                                    <p >Contract : {{project.get_contract_display}}</p>
                                    <p >Type : {{project.get_project_type_display}}</p>
                                    <p >Status : {{project.get_status_display}}</p> 
                            </div>
                        </div>
                   
                    </div>
                </div>
                
                <!-- /Doctor Widget -->	
                <!-- Doctor Details Tab -->
            <div class="card bg-white">
                <div class="card-body pt-0 bg-white">
                    <!-- Tab Menu -->
                    <nav class="user-tabs mb-4 bg-white">
                        <ul class="nav nav-tabs nav-tabs-bottom nav-justified">
                            <li class="nav-item">
                                <a class="nav-link active" href="#doc_overview" data-toggle="tab">Overview</a>
                            </li>
                            
                        </ul>
                </nav>
                <!-- /Tab Menu -->
                
                <!-- Tab Content -->
                <div class="tab-content pt-0">
                    <!-- Overview Content -->
                    <div role="tabpanel" id="doc_overview" class="tab-pane fade show active">
                        <div class="row">
                            <div class="col-md-12 col-lg-9">
                            
                                <!-- About Details -->
                                <div class="widget about-widget">
                                    <h4 class="widget-title">Project detail</h4>
                                    <p>{{project.description}} </p>
                                </div>
                                <!-- /About Details -->
                            </div>
                            
                        </div>
                    </div>
                </div>
        
</div>
<!-- /Page Wrapper -->

</div>
<!-- /Main Wrapper -->
{% endblock content %}

project/templates/project_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Project</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Project
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
                <div class="card-body">
                     <h4 class="card-title">Delete Project</h4>
                        <form action="{% url 'project:projectdelete' project.pk %}" method="post"  class="form-sample">
                            {% csrf_token %}
                            <p class="card-description">
                                Are you sure you want to delete <span class="badge badge-pill badge-light">  {{project.name}} </span> ? 
                            </p>  
                            <input type="submit" value="Submit" class="btn btn-primary mr-2" name="_save">
                        </form>
                </div>               
              </div>
            </div>
          
          </div>      
        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}

project/templates/project_edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Project</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Project
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
       
                  <h4 class="card-title">Edit Project</h4>
                <form action="{% url 'project:editproject' project.pk %}" method="post"  class="form-sample">
                    {% csrf_token %}
                    <p class="card-description">
                    
                    </p>
                                  {% comment %} row {% endcomment %}
                                    <div class="row">
                                        <div class="col-md-6">
                                          <div class="form-group row">
                                            <label class="col-sm-3 col-form-label" for="id_name">Project title</label>
                                            <div class="col-sm-9">
                                              <input  type="text" name="name"  id="id_name"  required="" class="form-control"  value="{{project.name}}">
                                            </div>
                                          </div>
                                        </div>
                                        <div class="col-md-6">
                                          <div class="form-group row">
                                            <label class="col-sm-3 col-form-label" for="id_started_date">Start date</label>
                                            <div class="col-sm-9">
                                              <input type="date" name="started_date"  id="id_started_date" required="" maxlength="200" class="form-control"  value="{{project.started_date|date:'Y-m-d'}}">
                                            </div>
                                          </div>
                                        </div>
                                    </div>
                                  {% comment %} end of row {% endcomment %}
                                  {% comment %} row {% endcomment %}
                                    <div class="row">
                                      <div class="col-md-6">
                                        <div class="form-group row">
                                          <label class="col-sm-3 col-form-label" for="id_deadline">Deadline</label>
                                          <div class="col-sm-9">
                                          <input type="date" name="deadline"   id="id_deadline" required=""  maxlength="200" class="form-control" value="{{project.deadline|date:'Y-m-d'}}">
                                          </div>
                                        </div>
                                      </div>
                                    
                                      <div class="col-md-6">
                                          <div class="form-group row">
                                            <label  class="col-sm-3 col-form-label" for="id_manager">Manager</label>              
                                            <div class="col-sm-9">
                                              <select name="manager" id="id_manager" class="form-control select bg-white">
                                                <option value="{{project.company}}"selected="">{{project.company}}</option>
                                                {% for employee in employees %} 
                                                <option value="{{employee.id}}">{{employee.name}} | {{employee.company}} </option>
                                                {% endfor %}
                                              </select>
                                            </div>
                                          </div>
                                      </div>
                                    </div>
                                  {% comment %} end of row {% endcomment %}
                                  {% comment %} row {% endcomment %}
                                    <div class="row">
                                      <div class="col-md-6">
                                        <div class="form-group row">				
                                          <label class="col-sm-3 col-form-label"  for="id_company">Company </label>
                                          <div class="col-sm-9">
                                            <select class="form-control"  name="company" id="id_company"> 
                                            <option value="{{project.manager}}"selected="">{{project.manager}}</option>
                                              {% for company in companies %}
                                              <option value="{{company.id}}">{{company.name}}</option>
                                              {% endfor %}	
                                            </select>
                                          </div>
                                        </div>
                                      </div>
                                      <div class="col-md-6">
                                        <div class="form-group row">
                                          <label class="col-sm-3 col-form-label" for="id_cost">Cost</label>
                                          <div class="col-sm-9">
                                          <input type="number" name="cost"   id="id_cost" required=""  maxlength="200" class="form-control" value="{{project.cost}}">
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  {% comment %} end of row {% endcomment %}
                                  {% comment %} row {% endcomment %}
                                    <div class="row">
                                        <div class="col-md-6">
                                          <div class="form-group row"> 
                                            <label class="col-sm-3 col-form-label"  for="id_contract">contract </label>
                                            <div class="col-sm-9">
                                              <select class="form-control"  name="contract" id="id_contract"> 
                                                <option value="{{project.contract}}"selected="">{{project.get_contract_display}}</option>
                                                <option value="H">hosting</option>
                                                <option value="A">annual</option>
                                                <option value="S">semi-anuual</option>
                                                <option value="Q">quarterly</option>
                                                <option value="AD">adverisement</option>
                                              </select>
                                            </div>
                                          </div>
                                        </div>
                                        <div class="col-md-6">
                                          <div class="form-group row"> 
                                            <label class="col-sm-3 col-form-label"  for="id_project_type">Type </label>
                                            <div class="col-sm-9">
                                              <select class="form-control"  name="project_type" id="id_project_type"> 
                                                <option value="{{project.project_type}}"selected="">{{project.get_project_type_display}}</option>
                                                <option value="EC">e-commerce</option>
                                                <option value="WS">web site</option>
                                                <option value="WA">web app</option>	
                                              </select>
                                          </div>
                                        </div>  
                                    </div>
                                  </div>
                                  {% comment %} end of row {% endcomment %}
                            {% comment %} row {% endcomment %}
                              <div class="row">
                                  <div class="col-md-6">
                                    <div class="form-group row"> 
                                      <label class="col-sm-3 col-form-label"  for="id_status"> status </label>
                                      <div class="col-sm-9">
                                        <select class="form-control"  name="status" id="id_status" > 
                                          <option value="{{project.status}}"selected="">{{project.get_status_display}}</option>
                                          <option value="CO">confirm</option>
                                          <option value="CP">completed</option>
                                          <option value="PE">pending </option>	
                                        </select>
                                      </div>
                                    </div>
                                  </div>   
                                  <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">description </label>
                                        <div class="col-sm-9">
                                          <input type="date" name="contract_expiration"  id="id_contract_expiration" value="{{project.contract_expiration|date:'Y-m-d'}}" required maxlength="200" class="form-control">

                                        </div>
                                    </div>
                                  </div>                         
                              </div>
                            {% comment %} end of row {% endcomment %}
                                  {% comment %} row {% endcomment %}
                              <div class="row">  
                                <div class="col-md-6">
                                  <div class="form-group row">
                                      <label class="col-sm-3 col-form-label" for="id_description">description </label>
                                      <div class="col-sm-9">
                                        <textarea name="description" cols="40" rows="10" class="form-control bg-white" id="id_description"> {{project.description |safe}}</textarea>          
                                      </div>
                                  </div>
                                </div>                         
                            </div>
                          {% comment %} end of row {% endcomment %}
                                
               
                            <input type="submit" value="Submit" class="btn btn-primary mr-2" name="_save">

                   
                      </form>
                      
           
              </div>
            </div>
          </div>


      
      
      
      
      
        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}