config/urls.py
# import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static


urlpatterns = [
     
     path('admin/', admin.site.urls),
     path ('', include('core.urls')), 
     path ('', include('accounts.urls')),    
     path ('meetings/', include('meetings.urls')), 
     path ('contact/', include('contact.urls')), 
     path ('project/', include('project.urls')), 
     
    #  path('__debug__/', include('debug_toolbar.urls')),
     
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

contact/urls.py
from django.urls import path
from . import views 
from .views import  CompanyListView, AddCompanyView, CompanyUpdateView, CompanyDetailView, CompanyDeleteView
from .views import  ClientListView, AddClientView, ClientUpdateView, ClientDetailView, ClientDeleteView
from .views import  LeadListView, AddLeadView, LeadUpdateView, LeadDetailView, LeadDeleteView, LeadsUpdateView
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'contact'

urlpatterns = [
  
   #company
  
   path('companylist', login_required(CompanyListView.as_view()), name='companylist'),
   path('addcompany', login_required(AddCompanyView.as_view()), name="addcompany"),
   path('editcompany/<int:pk>/', login_required(CompanyUpdateView.as_view()), name="editcompany"),
   path('companydetail/<int:pk>/', login_required(CompanyDetailView.as_view()), name="companydetail"),
   path('companydelete/<int:pk>/', login_required(CompanyDeleteView.as_view()), name="companydelete"),
  
  #CLIENT
   path('clientlist', login_required(ClientListView.as_view()), name='clientlist'),
   path('addclient', login_required(AddClientView.as_view()), name="addclient"),
   path('editclient/<int:pk>/', login_required(ClientUpdateView.as_view()), name="editclient"),
   path('clientdetail/<int:pk>/', login_required(ClientDetailView.as_view()), name="clientdetail"),
   path('clientdelete/<int:pk>/', login_required(ClientDeleteView.as_view()), name="clientdelete"),

   #LEADS
   path('leadlist', login_required(LeadListView.as_view()), name='leadlist'),
   path('addlead',  login_required(AddLeadView.as_view()), name="addlead"),
   path('editlead/<int:pk>/', login_required(LeadUpdateView.as_view()), name="editlead"),
   path('editleads/<int:pk>/', login_required(LeadsUpdateView.as_view()), name="editleads"),
   path('leaddetail/<int:pk>/', login_required(LeadDetailView.as_view()), name="leaddetail"),
   path('leaddelete/<int:pk>/', login_required(LeadDeleteView.as_view()), name="leaddelete"),
 

]

core/urls.py
from django.urls import path
from . import views 
from .views import IndexView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'core'

urlpatterns = [
  
  path('', login_required(IndexView.as_view()), name='index'),
   ]

project/urls.py
from django.urls import path 
from project.views import ProjectListView, AddProjectView, ProjectUpdateView, ProjectDetailView,ProjectDeleteView
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'project'

urlpatterns = [
  
   #project
   path('projectlist', login_required(ProjectListView.as_view()), name='projectlist'),
   path('addproject', login_required(AddProjectView.as_view()), name="addproject"),
   path('editproject/<int:pk>/', login_required(ProjectUpdateView.as_view()), name="editproject"),
   path('projectdetail/<int:pk>/', login_required(ProjectDetailView.as_view()), name="projectdetail"),
   path('projectdelete/<int:pk>/', login_required(ProjectDeleteView.as_view()), name="projectdelete"),

  
   

]

contact/models.py
from email.policy import default
from re import T
from django.db import models
from django.urls import reverse 
from tinymce import models as tinymce_models


# Create your models here.

# contact 
COMPANY_TYPE_CHOICES = (
    ('CL', 'client'),
    ('F', 'fournisseur'),
    ('P', 'partenaire'),
    ('CN', 'concurrent'),

)
PROJECT_TYPE_CHOICES = (
    ('EC', 'e-commerce'),
    ('WS', 'web site'),
    ('WA', 'web app'),
)

class Company(models.Model):
    name                = models.CharField(max_length=250)
    industry            = models.CharField(max_length=100, blank=True, null=True)
    annual_revenue      = models.DecimalField(max_digits=20 , decimal_places=0, blank=True, null=True)
    email               = models.EmailField(max_length=254,  blank=True, null=True)
    mobile              = models.CharField(max_length=13,  blank=True, null=True)
    website             = models.URLField(max_length=250, blank=True, null=True)
    adress              = models.CharField(max_length=250,  blank=True, null=True)
    rc_code             = models.CharField( max_length=150, null=True, blank=True)
    art_code            = models.CharField(max_length=150, null=True, blank=True)
    nif_code            = models.CharField( max_length=150, null=True, blank=True)
    nis_code            = models.CharField( max_length=150, null=True, blank=True)
    responsible_person  = models.CharField(max_length=100,  blank=True, null=True)
    source              = models.CharField(max_length=250, blank=True, null=True)
    company_type        = models.CharField(choices=COMPANY_TYPE_CHOICES, max_length=2, blank=True, null=True)
    project_type        = models.CharField(choices=PROJECT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    logo                = models.ImageField(upload_to='companies/', null=True, blank=True)  
    collab_start        = models.DateField(blank=True, null=True)
    created             = models.DateField(auto_now=True)
    updated             = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("contact:companydetail", kwargs={"pk": self.pk})

   
DECISION_TYPE_CHOICES= (
    ('1', '*'),
    ('2', '**'),
    ('3', '***'),
    ('4', '****'),
    ('5', '*****'),
)


class Employee(models.Model):
    name         = models.CharField(max_length=254)
    company      = models.ForeignKey(Company, blank=True, null=True, on_delete=models.CASCADE) 
    decision     = models.CharField(choices=DECISION_TYPE_CHOICES, max_length=2, blank=True, null=True)
    mobile       = models.CharField(max_length=13, blank=True, null=True)
    email        = models.EmailField(max_length=254, blank=True, null=True) 
    address      = models.CharField(max_length=250, blank=True, null=True)
    source       = models.CharField( max_length=250, blank=True, null=True)
    project_type = models.CharField(choices=PROJECT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    collab_start = models.DateField(blank=True, null=True)
    created      = models.DateField(auto_now=True)
    updated      = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("contact:clientdetail", kwargs={"pk": self.pk})

STATUS_TYPE_CHOICES= (
    ('I', 'inrested'),
    ('CA', 'call again'),
    ('NI', 'not intrested'), 
) 


class Lead(models.Model):
    company      = models.ForeignKey(Company, on_delete=models.SET_NULL, blank=True, null=True)
    source       = models.CharField( max_length=250, blank=True, null=True)
    project_type = models.CharField(choices=PROJECT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    status       = models.CharField(choices=STATUS_TYPE_CHOICES, max_length=2, blank=True, null=True)
    note         = tinymce_models.HTMLField( blank=True, null=True)
    created      = models.DateField(auto_now=True)
    updated      = models.DateField(auto_now_add=True)
    def __str__(self):
        return str(self.company)
    def get_absolute_url(self):
        return reverse("contact:leaddetail", kwargs={"pk": self.pk})
    
   

    

project/models.py
from django.db import models
from contact.models import Company, Employee
from tinymce import models as tinymce_models

# Create your models here.


PROJECT_TYPE_CHOICES = (
    ('EC', 'e-commerce'),
    ('WS', 'web site'),
    ('WA', 'web app'),
    
)
CONTRACT_TYPE_CHOICES = (
    ('H', 'hosting'),
    ('A', 'annual'),
    ('S', 'semi-annual'),
    ('Q', 'quarterly'),
    ('AD', 'adverisement'),
)
STATUS_TYPE_CHOICES= (
    ('CO', 'confirm'),
    ('CP', 'completed'),
    ('PE', 'pending'),
) 
class Project (models.Model): 
    name                    = models.CharField(max_length=254, blank=True)
    company                 = models.ForeignKey(Company, blank=True, null=True, on_delete=models.CASCADE) 
    manager                 = models.ForeignKey(Employee, blank=True, null=True, on_delete=models.CASCADE) 
    started_date            = models.DateField(blank=True, null=True) 
    deadline                = models.DateField(blank=True, null=True) 
    project_type            = models.CharField(choices=PROJECT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    contract                = models.CharField(choices=CONTRACT_TYPE_CHOICES, max_length=2, blank=True, null=True)
    contract_expiration     = models.DateField(blank=True, null=True) 
    cost                    = models.DecimalField(max_digits=20 , decimal_places=0, blank=True, null=True)
    status                  = models.CharField(choices=STATUS_TYPE_CHOICES, max_length=2, blank=True, null=True)
    description             = tinymce_models.HTMLField( blank=True, null=True)
    def __str__(self):
        return self.name
  

contact/forms.py
from django import forms
from django.forms import ModelForm
from .models import Company, Employee, Lead


class AddCompanyForm(ModelForm) :
    class Meta: 
        model = Company 
        fields = '__all__' 
        
class AddClientForm(ModelForm) :
    class Meta: 
        model = Employee 
        fields = '__all__' 


class AddLeadForm(ModelForm) :
    class Meta: 
        model = Lead
        fields = '__all__' 


class AddLeadsForm(ModelForm) :
    class Meta: 
        model = Lead
        fields =  ('status',)

contact/templates/client_add.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Contact</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Contact
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Add client</h4>
                <form action="{% url 'contact:addclient' %}" method="post"  class="form-sample">
                    {% csrf_token %}
                  <p class="card-description">
                   
                  </p>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_name">Name</label>
                        <div class="col-sm-9">
                          <input  type="text" name="name"  id="id_name"  required="" class="form-control">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_company">Company</label>
                        <div class="col-sm-9">
                          <select class="form-control bg-white"  name="company" id="id_company"> 
                                                <option value="">select a company</option>
                                            {% for company in companies %}
                                                <option value="{{company.id}}">{{company.name}}</option>
                                            {% endfor %}													
                          </select>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_decision">Decision</label>
                        <div class="col-sm-9">
                          <select class="form-control bg-white"  name="decision" id="id_decision"> 
                            <option value="1">*</option>
                            <option value="2">**</option>
                            <option value="3">***</option>	
                            <option value="4">****</option>
                            <option value="5">*****</option>													
                        </select>	
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label" for="id_slug">mobile</label>
                          <div class="col-sm-9">
                          <input type="text" name="mobile"  id="id_mobile" required="" pattern="^(?:0|\(?\+213\)?\s?|00213\s?)[1-79](?:[\.\-\s]?\d\d){4}$"  maxlength="200" maxlength="150"  class="form-control">
                          </div>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">	
                        <label class="col-sm-3 col-form-label" for="id_category">email </label>
                        <div class="col-sm-9">
                          <input  type="email" name="email"  id="id_email"  required="" class="form-control">
                        </div>
                      </div>
                    </div>
                     
                    <div class="col-md-6">
                      <div class="form-group row">	
                        <label class="col-sm-3 col-form-label" for="id_address">Address </label>
                        <div class="col-sm-9">
                          <input  type="text" name="address"  id="id_address"  required="" class="form-control">

                        </div>
                      </div>
                    </div>
                  </div>
                
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row"> 
                        <label class="col-sm-3 col-form-label" class="required" for="id_source">source</label>
                        <div class="col-sm-9">
                          <input  type="text" name="source"  id="id_source"  required="" class="form-control">  
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group row">
                          <label class="col-sm-3 col-form-label" for="id_project_type">project type  </label>
                          <div class="col-sm-9">
                            <select class="form-control"  name="project_type" id="id_project_type" > 
                              <option value="" selected="">Select company type</option>
                              <option value="EC">e-commerce</option>
                              <option value="WSF">web site</option>
                              <option value="WA">web app </option>	
                            </select>   
                          </div>
                      </div>
                    </div>            
                  </div> 
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row"> 
                        <label class="col-sm-3 col-form-label"  for="id_collab_start"> Collab start </label>
                        <div class="col-sm-9">                                     	
                          <input type="date" name="collab_start"  id="id_collab_start" class="form-control">
                      
                        </div>
                      </div>
                    </div>   
                  </div>
                  <button type="submit" class="btn btn-primary mr-2">Submit</button>
                </form>
              </div>
            </div>
          
          </div>


      
      
      
      
      
        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}

contact/templates/client_edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Contact</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Contact
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Edit client</h4>
                <form action="{% url 'contact:editclient' employee.pk %}" method="post"  class="form-sample">
                    {% csrf_token %}
                  <p class="card-description">
                   
                  </p>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_name">Name</label>
                        <div class="col-sm-9">
                          <input  type="text" name="name"  id="id_name"  required="" class="form-control" value="{{employee.name}}">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_company">Company</label>
                        <div class="col-sm-9">
                          <select class="form-control bg-white"  name="company" id="id_company"> 
                                                <option value="{{employee.company}}"selected="">{{employee.company}}</option>
                                            {% for company in companies %}
                                                <option value="{{company.id}}">{{company.name}}</option>
                                            {% endfor %}													
                          </select>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_decision">Decision</label>
                        <div class="col-sm-9">
                          <select class="form-control bg-white"  name="decision" id="id_decision"> 
                            <option value="{{employee.id_decision}}"selected="">{{employee.get_decision_display}}</option>
                            <option value="1">*</option>
                            <option value="2">**</option>
                            <option value="3">***</option>	
                            <option value="4">****</option>
                            <option value="5">*****</option>													
                        </select>	
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label" for="id_slug">mobile</label>
                          <div class="col-sm-9">
                          <input type="text" name="mobile"  id="id_mobile" required="" value="{{employee.mobile}}" pattern="^(?:0|\(?\+213\)?\s?|00213\s?)[1-79](?:[\.\-\s]?\d\d){4}$"  maxlength="200" maxlength="150"  class="form-control">
                          </div>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">	
                        <label class="col-sm-3 col-form-label" for="id_category">email </label>
                        <div class="col-sm-9">
                          <input  type="email" name="email"  id="id_email"  required="" value="{{employee.email}}" class="form-control">
                        </div>
                      </div>
                    </div>
                     
                    <div class="col-md-6">
                      <div class="form-group row">	
                        <label class="col-sm-3 col-form-label" for="id_address">Address </label>
                        <div class="col-sm-9">
                          <input  type="text" name="address"  id="id_address"  required="" value="{{employee.address}}"  class="form-control">

                        </div>
                      </div>
                    </div>
                  </div>
                
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row"> 
                        <label class="col-sm-3 col-form-label" class="required" for="id_source">source</label>
                        <div class="col-sm-9">
                          <input  type="text" name="source"  id="id_source"  value="{{employee.source}}" equired="" class="form-control">  
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group row">
                          <label class="col-sm-3 col-form-label" for="id_project_type">project type  </label>
                          <div class="col-sm-9">
                            <select class="form-control"  name="project_type" id="id_project_type" > 
                            <option value="{{employee.id_decision}}"selected="">{{employee.get_project_type_display}}</option>
                              <option value="EC">e-commerce</option>
                              <option value="WSF">web site</option>
                              <option value="WA">web app </option>	
                            </select>   
                          </div>
                      </div>
                    </div>            
                  </div> 
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row"> 
                        <label class="col-sm-3 col-form-label"  for="id_collab_start"> Collab start </label>
                        <div class="col-sm-9">                                     	
                          <input type="date" name="collab_start"  id="id_collab_start" value="{{employee.collab_start|date:'Y-m-d'}}" class="form-control">
                      
                        </div>
                      </div>
                    </div>   
                  </div>
                  <button type="submit" class="btn btn-primary mr-2">Submit</button>
                </form>
              </div>
            </div>
          
          </div>


      
      
      
      
      
        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}

contact/templates/lead_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>contact</title>
{% endblock %}

<div class="content-wrapper">
  <div class="page-header">
      <h3 class="page-title">
        contact
      </h3>
  </div> 
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-lg-4">
              <div class="border-bottom text-center pb-4">
                <h4> <a href="{% url 'contact:companydetail' lead.company.pk %}" style=" text-decoration:none; color:black;"> {{lead.company}} </a></h4>
              </div>                     
              <div class="border-bottom  py-4">
                <div class="py-4">
                  <p cla&tss="clearfix"> <span class="float-left"> </span> <span class="float-right text-muted">  </span> </p>
                  <p class="clearfix"> <span class="float-left" style="font-weight: bold;"> source</span> <span class="float-right text-muted"> {{lead.source}}</span></p>
                  <p class="clearfix"> <span class="float-left" style="font-weight: bold;"> type</span><span class="float-right text-muted"> {{lead.get_project_type_display}} </span> </p>
                  <p class="clearfix"> <span class="float-left" style="font-weight: bold;"> status</span><span class="float-right text-muted"> {{lead.get_status_display}}</span> </p>
                  <p class="clearfix"> <span class="float-left" style="font-weight: bold;"> created </span><span class="float-right text-info">{{lead.created}}</span> </p>
                </div>                                                       
              </div>
            </div>
            <div class="col-lg-8 pl-lg-5">
              <div class="d-flex justify-content-between">
                <div>
                  <h5>Overview</h5>
                  <div class="d-flex align-items-center">
                    <h5 class="mb-0 mr-2 text-muted"></h5>
                  </div>
                </div>
              </div>
              
              <div class="mt-4 py-2 border-top ">
                <ul class="nav profile-navbar">
                </ul>
              </div>
              <div class="profile-feed">
                  <div class="card">
                    <div class="card-body">
                      <h4 class="card-title"> Notes</h4>
                      <p class="card-description">
                        {{lead.note|safe}}
                      </p>
                   
                    </div>
                  </div>
                </div>

               
              </div>
            </div>
          </div> 
        
          
        </div>
        
      </div>
    </div>
  </div>
</div>
  <!-- main-panel ends -->         
{% endblock content %}

contact/templates/lead_edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Contact</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Contact
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Add lead</h4>
                <form action="{% url 'contact:editlead' lead.pk%}" method="post"  class="form-sample">
                    {% csrf_token %}
                  <p class="card-description">
                   
                  </p>
                  <div class="row">
                 
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_company">Company</label>
                        <div class="col-sm-9">
                          <select class="form-control bg-white"  name="company" id="id_company"> 
                                            <option value="{{lead.company}}"selected="">{{lead.company}}</option>
                                            {% for company in companies %}
                                                <option value="{{company.id}}">{{company.name}}</option>
                                            {% endfor %}													
                          </select>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_source">source</label>
                        <div class="col-sm-9">
                          <input  type="text" name="source"  id="id_source"  required="" class="form-control" value="{{lead.source}}">
                        </div>
                      </div>
                    </div>
                  </div>
            
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row"> 
                        <label class="col-sm-3 col-form-label"  for="id_status">status</label>
                        <div class="col-sm-9">
                          <select class="form-control"  name="status" id="id_status">
                            <option value="{{lead.status}}"selected="">{{lead.get_status_display}}</option>
                            <option value="I">inrested</option>
                            <option value="CA">call again</option>
                            <option value="NI">not intrested</option>
                          </select>  
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group row">
                          <label class="col-sm-3 col-form-label" for="id_project_type">project type  </label>
                          <div class="col-sm-9">
                            <select class="form-control"  name="project_type" id="id_project_type" > 
                              <option value="{{lead.project_type}}"selected="">{{lead.get_project_type_display}}</option>
                              <option value="EC">e-commerce</option>
                              <option value="WSF">web site</option>
                              <option value="WA">web app </option>	
                            </select>   
                          </div>
                      </div>
                    </div>            
                  </div> 
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group ">
                          <label class="col-sm-3 col-form-label" for="id_note">Note </label>
                          <div class="col-sm-6">
                              <textarea cols="40" rows="10" name="note"  id="id_note" class="form-control "  > {{lead.note |safe}}</textarea>
                          </div>
                      </div>
                  </div> 
                  </div>
                  <button type="submit" class="btn btn-primary mr-2">Submit</button>
                </form>
              </div>
            </div>
          
          </div>


      
      
      
      
      
        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}