config/urls.py
# import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static


urlpatterns = [
     
     path('admin/', admin.site.urls),
     path ('', include('core.urls')), 
     path ('', include('accounts.urls')),    
     path ('meetings/', include('meetings.urls')), 
     path ('contact/', include('contact.urls')), 
     path ('project/', include('project.urls')), 
     
    #  path('__debug__/', include('debug_toolbar.urls')),
     
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

core/urls.py
from django.urls import path
from . import views 
from .views import IndexView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'core'

urlpatterns = [
  
  path('', login_required(IndexView.as_view()), name='index'),
   ]

meetings/urls.py
from django.conf.urls import url
from django.urls import path
from meetings.views import CalendarView, EventDeleteView, EventUpdateView, EventsListView, EventView
from . import views
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'meetings'
urlpatterns = [
  
#calendar
 path('calendar', login_required(CalendarView.as_view()), name='calendar'),
 url(r'^event/new/$', login_required(views.event), name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', login_required(views.event), name='event_edit'),

path('event_list', login_required(EventsListView.as_view()), name='event_list'),
path('eventdelete/<int:pk>/', login_required(EventDeleteView.as_view()), name="eventdelete"),
path('edit_event/<int:pk>/', login_required(EventUpdateView.as_view()), name="edit_event"),
path('event_view/<int:pk>/', login_required(EventView.as_view()), name="event_view"),
 
]

 

meetings/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from contact.models import Company, Employee
from tinymce import models as tinymce_models
# Create your models here.

class Event(models.Model):
    title        = models.CharField(max_length=200)
    description  = tinymce_models.HTMLField( blank=True, null=True)
    start_date   = models.DateField()
    start_time   = models.TimeField(blank=True, null=True,)
    end_time     = models.TimeField(blank=True, null=True,)
    company      = models.ForeignKey(Company, blank=True, null=True, on_delete=models.CASCADE) 
    manager      = models.ForeignKey(Employee, blank=True, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    @property
    def get_html_url(self):
        url = reverse('meetings:event_view', args=(self.id,))
        return f'<a href="{url}" style="text-decoration:none; color:#392C70;"> {self.title} </a>'

    

    

meetings/forms.py
from django import forms
from django.forms import ModelForm, DateInput, TimeInput
from meetings.models import Event


class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    # widgets = {
    #   'start_date': DateInput(attrs={'type': 'date'}, format='%d-%m-%Y'),
    #   'start_time': TimeInput(attrs={'type': 'time'}, format='%H:%M:%S'),
    #   'end_time': TimeInput(attrs={'type': 'time'}, format='%H:%M:%S'),
    # }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    # self.fields['start_date'].input_formats = ('%d-%m-%Y')
    # self.fields['start_time'].input_formats = ('H:%M:%S',)
    # self.fields['end_time'].input_formats = ('H:%M:%S',) 

meetings/views.py
from datetime import datetime, timedelta, date
import calendar
from django.db.models.query import QuerySet
from django.db.models.query_utils import Q
from django.shortcuts import  redirect,render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.urls.base import reverse_lazy
from django.views import generic
from django.views.generic import (
    TemplateView,
    DetailView,
    ListView,
    UpdateView,
    ListView,
    DeleteView, 
    FormView
)
from django.views.generic.edit import CreateView
from django.utils.safestring import mark_safe
from pprint import pprint
from contact.models import Company, Employee
from meetings.models import Event
from meetings.utils import Calendar 
from meetings.forms import EventForm
from .filters import Eventsfilter
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
import logging
# Create your views here.
class RedirectPermissionRequiredMixin(PermissionRequiredMixin,):
    login_url = reverse_lazy('core:index')
    def handle_no_permission(self):
        return redirect(self.get_login_url())
#calendar
class CalendarView(RedirectPermissionRequiredMixin, generic.ListView):
    model = Event
    template_name = 'calendar.html'
    permission_required= 'meetings.view_event'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('meetings:calendar'))
    return render(request, 'event_add.html', {'form': form})

class EventDeleteView(RedirectPermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Event
    template_name= "event_delete.html"
    success_message = "Event deleted successfully "
    success_url = reverse_lazy('meetings:calendar')

class EventsListView(RedirectPermissionRequiredMixin,ListView): 
    template_name= "event_list.html"
    model = Event
    permission_required= 'meetings.view_meet'
    def get_context_data(self, **kwargs):
        context = super(EventsListView, self).get_context_data(**kwargs)
        context["event_count"] =Event.objects.all().count()
        filters= Eventsfilter(self.request.GET, queryset=Event.objects.all().order_by('start_date'))
        context["events"] = filters.qs
        return context
    

class EventUpdateView(RedirectPermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Event
    form_class=  EventForm
    template_name = 'event_edit.html' 
    permission_required= 'meetings.change_meet'
    success_message = "Event updated successfully "
    success_url = reverse_lazy('meetings:event_list')
    def get_context_data(self, **kwargs):
        context = super(EventUpdateView, self).get_context_data(**kwargs)
        context["companies"] = Company.objects.all()
        context["employees"] = Employee.objects.all()
        return context

    def form_invalid(self, form):
        pprint(form.errors)
        return super().form_invalid(form)


class EventView(RedirectPermissionRequiredMixin,DetailView):
    model = Event
    template_name= "event_detail.html"
    permission_required= 'meetings.view_meet'

meetings/templates/calendar.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Calendar</title>
{% endblock %}
<style>

    .calendar {
        width:98%;
        margin: auto;
        font-size: 13px;
        
      }
      
      .calendar tr, .calendar td {
       
      }
      
      .calendar th {
        background-color:#392C70;
        font-size: 16px;
        text-align: center; 
        border: 1px solid #ccc;
        color: #fff;

      }
      
      .calendar td  {
       
        color: #fff;
        
      
      }
      .case {
        text-align: initial;
        font-size: 18px;
        padding: 10px;
        border: 1px solid #ccc;
        
      }
      
      .calendar li {
        background-color:#CCC;
        text-align: center;
        font-size: 14px;
        border: 1px solid #ccc; 
        color: #fff;
      }
      .calendar ul {
        width:130px;
        height: 110px;
        text-align: center;
        color: #fff;

        
      }
      
      .month {
        font-size: 25px;
      }
      
      .date { 
        background-color:#392C70;
        text-align: center;
        font-size: 18px;
        border-right: 1px solid #ccc;
      }
      
      
      
      .left {
        float: left;
      }
      
      .right {
        float: right;
      }
      .a {
          text-decoration: none;
      }
      .btn {
        outline: none;
        color: #ccc;
        background-color: transparent;
        border: 1px solid #392C70;
      } 
      .btn:hover {
      
        color: #ccc;
       
      } 
      
      .clearfix {
        margin: 15px;
      }
      
      .meet{
        
        background-color: transparent;
        border: 1px solid #CCC;
      }  
      .hello {
        position:relative; 
        top:980px;
        background-color: rgb(104, 104, 34);
        border: 1px solid #CCC; 
      }      
</style>
<!-- Page Wrapper -->
<div class="page-wrapper">
    <div class="content container-fluid">
    
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Calendar</h3>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <div class="row ">
            <!-- Calendar -->
        
            <div class="col-sm-12">
                <div class="clearfix">
                    <a class="btn  left" href="{% url 'meetings:calendar' %}?{{ prev_month }}" style="color : black;"> Previous Month </a>
                    <a class="btn  right" href="{% url 'meetings:calendar' %}?{{ next_month }}" style="color : black;"> Next Month </a>
                    <a class="btn  right" href="{% url 'meetings:event_new' %}" style="color : black;"> New Event </a>
                </div>
            </div>
            <div class="col-sm-12 ">
      
                       {{ calendar }}
           
            </div>
        </div>                    
        </div>
    </div>			
</div>
<!-- /Page Wrapper -->

</div>
<!-- /Main Wrapper -->
<!-- <div class="hello">  
    <p> hello </p>
</div> -->
{% endblock content %}

meetings/templates/event_add.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Calendar</title>
{% endblock %}
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Calendar
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Add Event</h4>
                
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ field.label }} <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ field.label }} <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

                <form method="post"  class="form-sample">
                    {% csrf_token %}
                  <p class="card-description">
                  </p>
                  <div class="row">
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label class="col-sm-3 col-form-label" for="id_title">Title :</label>
                                <div class="col-sm-6">
                                    <input type="text" name="title"  id="id_title" class="form-control " required="" >
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label class="col-sm-3 col-form-label" for="id_start_date">Event start date :</label>
                                <div class="col-sm-6">
                                    <input type="date" name="start_date"  format="yyyy-mm-dd" id="id_start_date" class="form-control " required="" >
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label class="col-sm-3 col-form-label" for="id_start_time">Event start time :</label>
                                <div class="col-sm-6">
                                    <input type="time" step="1" name="start_time"  id="id_start_time" class="form-control " >
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label class="col-sm-3 col-form-label" for="id_end_time">Event end time :</label>
                                <div class="col-sm-6">
                                    <input type="time" step="1" name="end_time"  id="id_end_time" class="form-control " >
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label class="col-sm-3 col-form-label" for="id_description">Description :</label>
                                <div class="col-sm-6">
                                    <textarea cols="40" rows="10" name="description"  id="id_description" class="form-control "  ></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                        
                </div>
                    <div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        
                    </div>
                </form>
              </div>
            </div>
          
          </div> 

          <div>
            
        </div>
    <!-- main-panel ends -->
  </div>
 
  {% endblock content %}

meetings/templates/event_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Calendar</title>
{% endblock %}
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
          Calendar 
        </h3>
    </div> 
    <div class="row">
        <div class="col-lg-12">
            <div class="card px-2">
                <div class="card-body">
                    <div class="container-fluid">
                      <img src="{% static 'images/logo.png' %}" style="width:200px; height:80px; float:left;" alt="logo"/>
                      {% comment %} <h4 class="text-right my-5">{{event.title}}&nbsp;&nbsp;</h4>  {% endcomment %}
                      <p class="text-right my-5">Date : {{event.start_date}}</p>
                      <hr>
                    </div>
                    <div class="container-fluid d-flex justify-content-between">
                      <div class="col-lg-3 pl-0">
                        <p class="mt-5 mb-2"><b>{{event.title}}</b></p>
                        <p> <span style="font-weight: bold;">Meeting with :</span> {{event.company}}<br> <span style="font-weight: bold;">Manager :</span> {{event.manager}}<br></p>
                      </div>
                      <div class="col-lg-3 pr-0">
                        <p class="mt-5 mb-2 text-right"><b></b></p>
                        <p class="text-right"><br> <br><br><br><br></p>
                      </div>
                    </div>
                    {% comment %} <div class="container-fluid d-flex justify-content-between">
                      <div class="col-lg-3 pl-0">
                        <p class="mb-0 mt-5">Invoice Date : 23rd Jan 2016</p>
                        <p>Due Date : 25th Jan 2017</p>
                      </div>
                    </div> {% endcomment %}
                    <div class="container-fluid mt-5 d-flex justify-content-center w-100">
                      <div class="table-responsive w-100">
                        <h5>Notes :</h5>
                          <table class="table">
                            <thead>
                              <tr class="bg-dark text-white">
                                  <th></th>
                                  <th></th>
                                  <th class="text-right"></th>
                                  <th class="text-right"> </th>
                                  <th class="text-right"></th>
                                </tr>
                            </thead>
                            <tbody>
                                
                              <tr class="text-right">
                                <td class="text-left"> {{event.description|safe}}</td>
                             
                              </tr>
                          
                            </tbody>
                          </table>
                        </div>
                    </div>
                   
                    <div class="container-fluid w-100">
                      <a href="{% url 'meetings:edit_event' event.pk %}" class="btn btn-primary float-right mt-4 ml-2">Edit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- main-panel ends -->
</div>

{% endblock content %}

meetings/templates/event_edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Calendar</title>
{% endblock %}
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Calendar
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Event Report</h4>
                
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ field.label }} <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ field.label }} <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

                <form method="post"  action="{% url 'meetings:edit_event' event.pk %}" class="form-sample">
                    {% csrf_token %}
                  <p class="card-description">
                  </p>
                  <div class="row">
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label class="col-sm-3 col-form-label" for="id_title">Title :</label>
                                <div class="col-sm-6">
                                    <input type="text" name="title"  id="id_title" class="form-control " required="" value="{{event.title}}">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label class="col-sm-3 col-form-label" for="id_start_date">Event start time :</label>
                                <div class="col-sm-6">
                                    <input type="date" name="start_date"  id="id_start_date" class="form-control " selected required="" value="{{event.start_date|date:'Y-m-d'}}">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="form-group">
                                <label for="id_manager">Manager :</label>
                                <select name="manager" id="id_manager" class="form-control select" >
                                    <option value="{{event.manager}}"selected="">{{event.manager}}</option>
                                    {% for employee in employees %} 
                                    <option value="{{employee.id}}">{{employee.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="form-group">
                                <label for="id_company">Company :</label>
                                <select name="manager" id="id_company" class="form-control select bg-white">
                                    <option value="{{event.manager}}"selected="">{{event.company}}</option>
                                    {% for company in companies %}
                                    <option value="" selected=""></option>
                                    <option value="{{company.id}}">{{company.name}}</option>
                                    {% endfor %}			
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group ">
                                <label class="col-sm-3 col-form-label" for="id_description">Description :</label>
                                <div class="col-sm-6">
                                    <textarea cols="40" rows="10" name="description"  id="id_description" class="form-control " value="{{event.description}}"> {{event.description}}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                        
                </div>
                    <div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        
                    </div>
                </form>
              </div>
            </div>
          
          </div> 

          <div>
            
        </div>
    <!-- main-panel ends -->
  </div>
 
  {% endblock content %}

meetings/templates/event_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Calendar</title>
{% endblock %}
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Calendar
              </h3>
          </div>
          <div>
            <div class="col-md-6 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title mb-0">Total</h4>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-inline-block pt-3">
                                <div class="d-md-flex">
                                    <h2 class="mb-0">{{ event_count }} </h2>
                                    
                                </div>
                            </div>
                            <div class="d-inline-block">
                                <i class=" fas  fa-solid fa-calendar-check text-info icon-lg"></i>                     
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div> 
        <div class="card">
            <div class="card-body">
              <h4 class="card-title">Events List</h4>
              <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <div id="order-listing_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            

                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="order-listing" class="table dataTable no-footer" role="grid" aria-describedby="order-listing_info">
                                            <thead style="background-color: #2b2155; color:#fff;">
                                                <tr role="row">
                                                    <th style="width:400px;">Title </th>
                                                    <th style="width:400px;">Date</th>
                                                    <th style="width:400px;">Notes</th>
                                                    <th style="width:400px;" >Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody> 
                                                {% for event in events %}
                                            <tr role="row" class="odd">
                                                    <td ><span class="badge badge-pill badge-light">{{event.title}}</span> </td>
                                                    <td class="d-block text-info">{{event.start_date}}</td>
                                                    <td >{{event.description|safe}}</td>
                                              
                                                    <td >
                                                    <a href="{% url 'meetings:event_view' event.pk %}">
                                                        <button class="btn btn-outline-primary">View</button></a>
                                                       
                                                    <a href="{% url 'meetings:edit_event' event.pk %}">
                                                    <button class="btn btn-outline-primary">Edit</button></a>
                                                    <a href="#">
                                                        <button class="btn btn-outline-primary">Delete</button></a>
                                                    </td>
                                                </tr>    
                                            {% endfor %}
                                            </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                            {% comment %} <div class="row">
                                                <div class="col-sm-12 col-md-5">
                                                    <div class="dataTables_info" id="order-listing_info" role="status" aria-live="polite">Showing 1 to 10 of 10 entries</div>
                                                </div>
                                                <div class="col-sm-12 col-md-7">
                                                    <div class="dataTables_paginate paging_simple_numbers" id="order-listing_paginate">
                                                        <ul class="pagination">
                                                            <li class="paginate_button page-item previous disabled" id="order-listing_previous">
                                                                <a href="#" aria-controls="order-listing" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
                                                            </li>
                                                            <li class="paginate_button page-item active"><a href="#" aria-controls="order-listing" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                                                            <li class="paginate_button page-item next disabled" id="order-listing_next"><a href="#" aria-controls="order-listing" data-dt-idx="2" tabindex="0" class="page-link">Next</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div> {% endcomment %}
                                        </div>
                                        </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
      
    <!-- main-panel ends -->
  </div>
 
  {% endblock content %}