accounts/urls.py
from django.urls import path
from .views import SignupView, SignupsuccessView
from django.contrib.auth import views as auth_views
from .froms import AuthenticationForm
from django.contrib.auth.decorators import login_required, permission_required
from .views import UserView, UserUpdateView
app_name= 'accounts'

urlpatterns = [
  
 path('signup/', SignupView.as_view(), name="signup"),
 path('signup_success/', SignupsuccessView.as_view(), name="signup_success"),
 path('login/', auth_views.LoginView.as_view(template_name="login.html",form_class=AuthenticationForm,),name="login",),
 path('logout/' , auth_views.LogoutView.as_view(), name= 'logout' ),
 path('userdetail', login_required(UserView.as_view()), name="userdetail"),
 path('edituser/<int:pk>/', login_required(UserUpdateView.as_view()), name="edituser"),
]

config/urls.py
# import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static


urlpatterns = [
     
     path('admin/', admin.site.urls),
     path ('', include('core.urls')), 
     path ('', include('accounts.urls')),    
     path ('meetings/', include('meetings.urls')), 
     path ('contact/', include('contact.urls')), 
     path ('project/', include('project.urls')), 
     
    #  path('__debug__/', include('debug_toolbar.urls')),
     
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

contact/urls.py
from django.urls import path
from . import views 
from .views import  CompanyListView, AddCompanyView, CompanyUpdateView, CompanyDetailView, CompanyDeleteView
from .views import  ClientListView, AddClientView, ClientUpdateView, ClientDetailView, ClientDeleteView
from .views import  LeadListView, AddLeadView, LeadUpdateView, LeadDetailView, LeadDeleteView, LeadsUpdateView
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'contact'

urlpatterns = [
  
   #company
  
   path('companylist', login_required(CompanyListView.as_view()), name='companylist'),
   path('addcompany', login_required(AddCompanyView.as_view()), name="addcompany"),
   path('editcompany/<int:pk>/', login_required(CompanyUpdateView.as_view()), name="editcompany"),
   path('companydetail/<int:pk>/', login_required(CompanyDetailView.as_view()), name="companydetail"),
   path('companydelete/<int:pk>/', login_required(CompanyDeleteView.as_view()), name="companydelete"),
  
  #CLIENT
   path('clientlist', login_required(ClientListView.as_view()), name='clientlist'),
   path('addclient', login_required(AddClientView.as_view()), name="addclient"),
   path('editclient/<int:pk>/', login_required(ClientUpdateView.as_view()), name="editclient"),
   path('clientdetail/<int:pk>/', login_required(ClientDetailView.as_view()), name="clientdetail"),
   path('clientdelete/<int:pk>/', login_required(ClientDeleteView.as_view()), name="clientdelete"),

   #LEADS
   path('leadlist', login_required(LeadListView.as_view()), name='leadlist'),
   path('addlead',  login_required(AddLeadView.as_view()), name="addlead"),
   path('editlead/<int:pk>/', login_required(LeadUpdateView.as_view()), name="editlead"),
   path('editleads/<int:pk>/', login_required(LeadsUpdateView.as_view()), name="editleads"),
   path('leaddetail/<int:pk>/', login_required(LeadDetailView.as_view()), name="leaddetail"),
   path('leaddelete/<int:pk>/', login_required(LeadDeleteView.as_view()), name="leaddelete"),
 

]

core/urls.py
from django.urls import path
from . import views 
from .views import IndexView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'core'

urlpatterns = [
  
  path('', login_required(IndexView.as_view()), name='index'),
   ]

meetings/urls.py
from django.conf.urls import url
from django.urls import path
from meetings.views import CalendarView, EventDeleteView, EventUpdateView, EventsListView, EventView
from . import views
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'meetings'
urlpatterns = [
  
#calendar
 path('calendar', login_required(CalendarView.as_view()), name='calendar'),
 url(r'^event/new/$', login_required(views.event), name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', login_required(views.event), name='event_edit'),

path('event_list', login_required(EventsListView.as_view()), name='event_list'),
path('eventdelete/<int:pk>/', login_required(EventDeleteView.as_view()), name="eventdelete"),
path('edit_event/<int:pk>/', login_required(EventUpdateView.as_view()), name="edit_event"),
path('event_view/<int:pk>/', login_required(EventView.as_view()), name="event_view"),
 
]

 

project/urls.py
from django.urls import path 
from project.views import ProjectListView, AddProjectView, ProjectUpdateView, ProjectDetailView,ProjectDeleteView
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'project'

urlpatterns = [
  
   #project
   path('projectlist', login_required(ProjectListView.as_view()), name='projectlist'),
   path('addproject', login_required(AddProjectView.as_view()), name="addproject"),
   path('editproject/<int:pk>/', login_required(ProjectUpdateView.as_view()), name="editproject"),
   path('projectdetail/<int:pk>/', login_required(ProjectDetailView.as_view()), name="projectdetail"),
   path('projectdelete/<int:pk>/', login_required(ProjectDeleteView.as_view()), name="projectdelete"),

  
   

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block title %}
<title>base</title>
{% endblock %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Stock</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
  <!-- autocomplet -->
  {% comment %} <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />  {% endcomment %}
 
   <!-- endautocomplet -->
</head>
{% include 'navbar.html' %}
{% include 'sidebar.html' %}

<body>
            {%block scripts%}
            {%endblock scripts%}
            {% block content %}
            
            {% endblock content %}

  <!-- plugins:js -->
  <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->

  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'js/misc.js' %}"></script>
  <script src="{% static 'js/settings.js' %}"></script>
  <script src="{% static 'js/todolist.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->

  <!-- End custom js for this page-->
    <!-- Custom js for this page-->
    <script src="{% static 'js/formpickers.js' %}"></script>
    <script src="{% static 'js/form-addons.js' %}"></script>
    <script src="{% static 'js/x-editable.js' %}"></script>
    <script src="{% static 'js/dropify.js' %}"></script>
    <script src="{% static 'js/dropzone.js' %}"></script>
    <script src="{% static 'js/jquery-file-upload.js' %}"></script>
    <script src="{% static 'js/formpickers.js' %}"></script>
    <script src="{% static 'js/form-repeater.js' %}"></script>
    <script src="{% static 'js/chart.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <!-- End custom js for this page-->
  {% comment %} <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> 
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
  <script src="{% static 'jquery-ui-1.13.1.custom/jquery-ui.js' %}"></script> {% endcomment %}
  {% block extrasj %}
  {% endblock extrasj %}
 <!-- Vendor JS Files -->
 {% comment %} <script src="{% static 'vendors/aos/aos.js' %}"></script>
 <script src="{% static 'vendors/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'vendors/glightbox/js/glightbox.min.js' %}"></script>
 <script src="{% static 'vendors/isotope-layout/isotope.pkgd.min.js' %}"></script>
 <script src="{% static 'vendors/swiper/swiper-bundle.min.js' %}"></script>
 <script src="{% static 'vendors/waypoints/noframework.waypoints.js' %}"></script>
 <script src="{% static 'vendors/php-email-form/validate.js' %}"></script> {% endcomment %}

 <!-- Template Main JS File -->
 {% comment %} <script src="{% static 'js/main.js' %}"></script> {% endcomment %}
 <script language="JavaScript"> 
  
</script>

</body>



</html>

templates/navbar.html
{% load static %}
<div class="container-scroller">
      <!-- partial:../../partials/_navbar.html -->
      <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row default-layout-navbar">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo" href="/"><img src="{% static 'images/logo.png' %}" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="/"><img src="{% static 'images/logo-mini.png' %}" alt="logo"/></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="fas fa-bars"></span>
          </button>

            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible text-center" role="alert"  style="margin-left:400px; margin-top:7px;"> 
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message|safe }}
                    </div>
                {% endfor %}
            {% endif %}
          <!-- message -->
          {% comment %} {% if messages %}
          <ul class="navbar-nav messages" style="margin-left:400px;">
                  {% for message in messages %}
                  <h6 {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }} </h6>
                  {% endfor %}
          </ul> 
          {% endif %}  {% endcomment %}
           <!-- message -->
     
          <ul class="navbar-nav navbar-nav-right"> 
            {% comment %} <li class="nav-item dropdown">
              <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                <i class="fas fa-bell mx-0"></i>
                <span class="count">16</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                <a class="dropdown-item">
                  <p class="mb-0 font-weight-normal float-left">You have 16 new notifications
                  </p>
                  <span class="badge badge-pill badge-warning float-right">View all</span>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-danger">
                      <i class="fas fa-exclamation-circle mx-0"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-medium">Application Error</h6>
                    <p class="font-weight-light small-text">
                      Just now
                    </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-warning">
                      <i class="fas fa-wrench mx-0"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-medium">Settings</h6>
                    <p class="font-weight-light small-text">
                      Private message
                    </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-info">
                      <i class="far fa-envelope mx-0"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-medium">New user registration</h6>
                    <p class="font-weight-light small-text">
                      2 days ago
                    </p>
                  </div>
                </a>
              </div> 
            </li> {% endcomment %}
          
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
              {% if user.picture %} 
                <img src="{{user.picture.url}}" alt="profile"/>
              {% else %} 
                <img  src="{% static 'images/avatar.png' %}" alt="logo"/> 
              {% endif %}
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                <a class="dropdown-item"  href="{% url 'accounts:userdetail' %}">
                {% if user.picture %} 
                  <img src="{{user.picture.url}}" alt="profile"/>
                {% else %} 
                <img  src="{% static 'images/avatar.png' %}" alt="logo"/> 
                {% endif %}
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"  href="{% url 'accounts:logout' %}">
                  <i class="fas fa-power-off text-primary"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
      
        </div>
      </nav>
      <!-- partial -->

    

templates/sidebar.html
{% load static %}



    <div class="container-fluid page-body-wrapper">

          <!-- partial:../../partials/_settings-panel.html -->
          <div class="theme-setting-wrapper">
            <div id="settings-trigger"><i class="fas fa-fill-drip"></i></div>
            <div id="theme-settings" class="settings-panel">
              <i class="settings-close fa fa-times"></i>
              <p class="settings-heading">SIDEBAR SKINS</p>
              <div class="sidebar-bg-options selected" id="sidebar-light-theme"><div class="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
              <div class="sidebar-bg-options" id="sidebar-dark-theme"><div class="img-ss rounded-circle bg-dark border mr-3"></div>Dark</div>
              <p class="settings-heading mt-2">HEADER SKINS</p>
              <div class="color-tiles mx-0 px-4">
                <div class="tiles primary"></div>
                <div class="tiles success"></div>
                <div class="tiles warning"></div>
                <div class="tiles danger"></div>
                <div class="tiles info"></div>
                <div class="tiles dark"></div>
                <div class="tiles default"></div>
              </div>
            </div>
          </div>

     <!-- partial:../../partials/_sidebar.html -->
     <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="profile-image">
                {% comment %} <img  src="{{user.display_picture}}" alt="image"/> {% endcomment %}

              {% if user.picture %} 
                  <img  src="{{user.picture.url}}" alt="image"/>
              {% else %} 
                  <img  src="{% static 'images/avatar.png' %}" alt="logo"/> 
              {% endif %} 
              </div>
              <div class="profile-name">
                <p class="name">
                  <a href="{% url 'accounts:userdetail' %}" style="text-decoration:none; color:black;">{{ user.get_username }} </a>
                </p>
                <p class="designation">
                  
                </p>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/" >
              <i class="fa fa-home menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#editors" aria-expanded="false" aria-controls="editors">
              <i class="fas fa-solid fa-calendar menu-icon"></i> 
              <span class="menu-title" >Calendar</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="editors">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"><a class="nav-link" href="{% url 'meetings:calendar' %}" style="text-decoration : none;"> Calendar</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'meetings:event_list' %}"   style="text-decoration : none;"> Reports </a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#charts" aria-expanded="false" aria-controls="charts">
              <i class="fas fa-solid fa-address-book menu-icon"></i> 
              <span class="menu-title">Contact</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="charts">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'contact:companylist' %}"  style="text-decoration:none;">Company list</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'contact:clientlist' %}" style="text-decoration:none;">Client list</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'contact:leadlist' %}" style="text-decoration:none;">Leads</a></li>
              </ul>
              </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'project:projectlist' %}"  >
              <i class="fa fa fa-tasks menu-icon"></i> 
              <span class="menu-title">Project</span>
            </a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="#"  >
              <i class="fas fa-solid fa-moon menu-icon"></i> 
              <span class="menu-title">Dark mode</span> 
            </a>
          </li> {% endcomment %}
          {% comment %} <li class="nav-item"> 
            <a class="nav-link" data-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
              <i class="fas fa-solid fa-money-bill menu-icon"></i> 
              <span class="menu-title">Cashflow</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="tables">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="" style="text-decoration:none;">Accounts</a></li>
                <li class="nav-item"> <a class="nav-link" href="" style="text-decoration:none;">Transaction</a></li> 
              </ul>
            </div>
          </li> {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#icons" aria-expanded="false" aria-controls="icons">
              <i class="fas fa-solid fa-receipt menu-icon"></i> 
              <span class="menu-title" >Invoice</span> 
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="icons">
              <ul class="nav flex-column sub-menu"> 
                <li class="nav-item"> <a class="nav-link" href="" style="text-decoration:none;">Invoice list</a></li>
              </ul>
            </div>
          </li> {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-advanced" aria-expanded="false" aria-controls="ui-advanced">
              <i class="fas fa-solid fa-headset menu-icon"></i>
              <span class="menu-title">Client service</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-advanced">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="" style="text-decoration:none;">ticketing</a></li>
              </ul>
            </div>
          </li> {% endcomment %}

          
        </ul>
      </nav>
      <!-- partial -->